joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - JOINT1
      - JOINT2
      - JOINT3
